FROM flink:1.17.2

USER root
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir numpy apache-flink==1.17.2 kafka-python && \
    ln -sf /usr/bin/python3 /usr/bin/python

COPY ./flink-usrlib/flink-sql-connector-kafka-1.17.2.jar /opt/flink/lib/

USER flink