FROM flink:1.20

USER root
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir numpy apache-flink==1.20 kafka-python && \
    ln -sf /usr/bin/python3 /usr/bin/python

COPY ./flink-usrlib/flink-sql-connector-kafka-3.3.0-1.20.jar /opt/flink/lib/

USER flink